substitutions:
  _HUGO_VERSION: '0.55.6'
  _HUGO_HASH: '6bf54c2833727ae592b9810e54b7b9a3c02f88e9'

images:
  - 'gcr.io/$PROJECT_ID/$REPO_NAME:commit-$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/$REPO_NAME:$_HUGO_VERSION'
  - 'gcr.io/$PROJECT_ID/$REPO_NAME:latest'

steps:
  - id: Build
    name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - --build-arg
      - HUGO_VERSION=$_HUGO_VERSION
      - --build-arg
      - HUGO_HASH=$_HUGO_HASH
      - -t
      - gcr.io/$PROJECT_ID/$REPO_NAME:commit-$SHORT_SHA
      - .

  - id: Tag Version
    name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/$PROJECT_ID/$REPO_NAME:commit-$SHORT_SHA', 'gcr.io/$PROJECT_ID/$REPO_NAME:$_HUGO_VERSION']

  - id: Tag Latest
    name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/$PROJECT_ID/$REPO_NAME:commit-$SHORT_SHA', 'gcr.io/$PROJECT_ID/$REPO_NAME:latest']

  - id: Push
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME']
